# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9FSJta60QVtolB6AKgoLVETpqSaxHeU
"""

print(a)
a=123

print(bool(1))

print(int(100))

print(float(1))

s=str('Python')
s[0]='Q'

a=1
print(a,id(a))
a='Python'
print(a,id(a))

x=1
y=x
print(id(x),id(y))
print(x,y)

b=ture
print(b)

x=[1,2,3]
y=[1,2,3]
print(id(x),id(y))
print(x is y)
print(x==y)